name: Pull Request

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn lint
    - run: yarn test:coverage -r lcov | tail -n +3 | head -n -1 > coverage/lcov.info
    - uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        delete-old-comments: true
        filter-changed-files: true
        github-token: ${{ secrets.CODE_COVERAGE_REPORT_TOKEN }}
