name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t wilgnne/technical-challenge-api:latest
      - name: publish
        run: |
          docker login -u wilgnne -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push wilgnne/technical-challenge-api:latest
